image player 1f = im.Flip("characters/player/char_player_01.png", horizontal=True)
image player 2f = im.Flip("characters/player/char_player_02.png", horizontal=True)
image player 3f = im.Flip("characters/player/char_player_03.png", horizontal=True)
image player 4f = im.Flip("characters/player/char_player_04.png", horizontal=True)
image player 5f = im.Flip("characters/player/char_player_05.png", horizontal=True)
image player 6f = im.Flip("characters/player/char_player_06.png", horizontal=True)
image player 7f = im.Flip("characters/player/char_player_07.png", horizontal=True)
image player 8f = im.Flip("characters/player/char_player_08.png", horizontal=True)
image player 8bf = im.Flip("characters/player/char_player_08b.png", horizontal=True)
image player 9f = im.Flip("characters/player/char_player_09.png", horizontal=True)
image player 10f = im.Flip("characters/player/char_player_10.png", horizontal=True)
image player 11f = im.Flip("characters/player/char_player_11.png", horizontal=True)
image player 12f = im.Flip("characters/player/char_player_12.png", horizontal=True)
image player 13f = im.Flip("characters/player/char_player_13.png", horizontal=True)
image player 14f = im.Flip("characters/player/char_player_14.png", horizontal=True)
image player 15f = im.Flip("characters/player/char_player_15.png", horizontal=True)
image player 16f = im.Flip("characters/player/char_player_16.png", horizontal=True)
image player 17f = im.Flip("characters/player/char_player_17.png", horizontal=True)
image player 18f = im.Flip("characters/player/char_player_18.png", horizontal=True)
image player 19f = im.Flip("characters/player/char_player_19.png", horizontal=True)
image player 20f = im.Flip("characters/player/char_player_20.png", horizontal=True)
image player 21f = im.Flip("characters/player/char_player_21.png", horizontal=True)
image player 22f = im.Flip("characters/player/char_player_22.png", horizontal=True)
image player 23f = im.Flip("characters/player/char_player_23.png", horizontal=True)
image player 24f = im.Flip("characters/player/char_player_24.png", horizontal=True)
image player 25f = im.Flip("characters/player/char_player_25.png", horizontal=True)
image player 26f = im.Flip("characters/player/char_player_26.png", horizontal=True)
image player 27f = im.Flip("characters/player/char_player_27.png", horizontal=True)
image player 28f = im.Flip("characters/player/char_player_28.png", horizontal=True)
image player 29f = im.Flip("characters/player/char_player_29.png",xoffset=-8, horizontal=True)
image player 30f = im.Flip("characters/player/char_player_30.png", horizontal=True)
image player 31f = im.Flip("characters/player/char_player_31.png", horizontal=True)
image player 32f = im.Flip("characters/player/char_player_32.png", horizontal=True)
image player 33f = im.Flip("characters/player/char_player_33.png", horizontal=True)
image player 34f = im.Flip("characters/player/char_player_34.png", horizontal=True)
image player 35f = im.Flip("characters/player/char_player_35.png", horizontal=True)
image player 36f = im.Flip("characters/player/char_player_36.png", horizontal=True)
image player 37f = im.Flip("characters/player/char_player_37.png", horizontal=True)
image player 38f = im.Flip("characters/player/char_player_38.png", horizontal=True)
image player 39f = im.Flip("characters/player/char_player_39.png", horizontal=True)
image player 40f = im.Flip("characters/player/char_player_40.png", horizontal=True)
image player 41f = im.Flip("characters/player/char_player_41.png", horizontal=True)
image player 42f = im.Flip("characters/player/char_player_42.png", horizontal=True)
image player 43f = im.Flip("characters/player/char_player_43.png", horizontal=True)
image player 44f = im.Flip("characters/player/char_player_44.png", horizontal=True)
image player 45f = im.Flip("characters/player/char_player_45.png", horizontal=True)
image player 46f = im.Flip("characters/player/char_player_46.png", horizontal=True)
image player 47f = im.Flip("characters/player/char_player_47.png", horizontal=True)
image player 48f = im.Flip("characters/player/char_player_48.png", horizontal=True)
image player 49f = im.Flip("characters/player/char_player_49.png", horizontal=True)
image player 50f = im.Flip("characters/player/char_player_50.png", horizontal=True)
image player 51f = im.Flip("characters/player/char_player_51.png", horizontal=True)
image player 52f = im.Flip("characters/player/char_player_52.png", horizontal=True)
image player 53f = im.Flip("characters/player/char_player_53.png", horizontal=True)
image player 54f = im.Flip("characters/player/char_player_54.png", horizontal=True)
image player 55f = im.Flip("characters/player/char_player_55.png", horizontal=True)
image player 56f = im.Flip("characters/player/char_player_56.png", horizontal=True)
image player 57f = im.Flip("characters/player/char_player_57.png", horizontal=True)
image player 58f = im.Flip("characters/player/char_player_58.png", horizontal=True)
image player 59f = im.Flip("characters/player/char_player_59.png", horizontal=True)
image player 60f = im.Flip("characters/player/char_player_60.png", horizontal=True)
image player 61f = im.Flip("characters/player/char_player_61.png", horizontal=True)
image player 62f = im.Flip("characters/player/char_player_62.png", horizontal=True)
image player 63f = im.Flip("characters/player/char_player_63.png", horizontal=True)
image player 64f = im.Flip("characters/player/char_player_64.png", horizontal=True)
image player 65f = im.Flip("characters/player/char_player_65.png", horizontal=True)
image player 66f = im.Flip("characters/player/char_player_66.png", horizontal=True)
image player 67f = im.Flip("characters/player/char_player_67.png", horizontal=True)
image player 67bf = im.Flip("characters/player/char_player_67b.png", horizontal=True)
image player 67cf = im.Flip("characters/player/char_player_67c.png", horizontal=True)
image player 68f = im.Flip("characters/player/char_player_68.png", horizontal=True)
image player 68bf = im.Flip("characters/player/char_player_68b.png", horizontal=True)
image player 69f = im.Flip("characters/player/char_player_69.png", horizontal=True)
image player 70f = im.Flip("characters/player/char_player_70.png", horizontal=True)
image player 71f = im.Flip("characters/player/char_player_71.png", horizontal=True)
image player 72f = im.Flip("characters/player/char_player_72.png", horizontal=True)
image player 73f = im.Flip("characters/player/char_player_73.png", horizontal=True)
image player 74f = im.Flip("characters/player/char_player_74.png", horizontal=True)
image player 75f = im.Flip("characters/player/char_player_75.png", horizontal=True)
image player 76f = im.Flip("characters/player/char_player_76.png", horizontal=True)
image player 77f = im.Flip("characters/player/char_player_77.png", horizontal=True)
image player 78f = im.Flip("characters/player/char_player_78.png", horizontal=True)
image player 79f = im.Flip("characters/player/char_player_79.png", horizontal=True)
image player 80f = im.Flip("characters/player/char_player_80.png", horizontal=True)
image player 81f = im.Flip("characters/player/char_player_81.png", horizontal=True)
image player 82f = im.Flip("characters/player/char_player_82.png", horizontal=True)
image player 83f = im.Flip("characters/player/char_player_83.png", horizontal=True)
image player 84f = im.Flip("characters/player/char_player_84.png", horizontal=True)
image player 85f = im.Flip("characters/player/char_player_85.png", horizontal=True)
image player 86f = im.Flip("characters/player/char_player_86.png", horizontal=True)
image player 87f = im.Flip("characters/player/char_player_87.png", horizontal=True)
image player 88f = im.Flip("characters/player/char_player_88.png", horizontal=True)
image player 89f = im.Flip("characters/player/char_player_89.png", horizontal=True)
image player 90f = im.Flip("characters/player/char_player_90.png", horizontal=True)
image player 91f = im.Flip("characters/player/char_player_91.png", horizontal=True)
image player 92f = im.Flip("characters/player/char_player_92.png", horizontal=True)
image player 93f = im.Flip("characters/player/char_player_93.png", horizontal=True)
image player 94f = im.Flip("characters/player/char_player_94.png", horizontal=True)
image player 95f = im.Flip("characters/player/char_player_95.png", horizontal=True)
image player 96f = im.Flip("characters/player/char_player_96.png", horizontal=True)
image player 97f = im.Flip("characters/player/char_player_97.png", horizontal=True)

image player 99f = im.Flip("characters/player/char_player_99.png", horizontal=True)
image player 100f = im.Flip("characters/player/char_player_100.png", horizontal=True)
image player 100bf = im.Flip( "characters/player/char_player_100b.png", horizontal=True)
image player 101f = im.Flip("characters/player/char_player_101.png", horizontal=True)
image player 101bf = im.Flip( "characters/player/char_player_101b.png", horizontal=True)
image player 102f = im.Flip("characters/player/char_player_102.png", horizontal=True)
image player 103f = im.Flip("characters/player/char_player_103.png", horizontal=True)
image player 104f = im.Flip("characters/player/char_player_104.png", horizontal=True)
image player 105f = im.Flip("characters/player/char_player_105.png", horizontal=True)
image player 106f = im.Flip("characters/player/char_player_106.png", horizontal=True)
image player 107f = im.Flip("characters/player/char_player_107.png", horizontal=True)
image player 108f = im.Flip("characters/player/char_player_108.png", horizontal=True)
image player 109f = im.Flip("characters/player/char_player_109.png", horizontal=True)
image player 110f = im.Flip("characters/player/char_player_110.png", horizontal=True)
image player 111f = im.Flip("characters/player/char_player_111.png", horizontal=True)
image player 112f = im.Flip("characters/player/char_player_112.png", horizontal=True)
image player 113f = im.Flip("characters/player/char_player_113.png", horizontal=True)
image player 114f = im.Flip("characters/player/char_player_114.png", horizontal=True)
image player 115f = im.Flip("characters/player/char_player_115.png", horizontal=True)
image player 116f = im.Flip("characters/player/char_player_116.png", horizontal=True)
image player 117f = im.Flip("characters/player/char_player_117.png", horizontal=True)
image player 118f = im.Flip("characters/player/char_player_118.png", horizontal=True)
image player 119f = im.Flip("characters/player/char_player_119.png", horizontal=True)
image player 120f = im.Flip("characters/player/char_player_120.png", horizontal=True)
image player 121f = im.Flip("characters/player/char_player_121.png", horizontal=True)
image player 122f = im.Flip("characters/player/char_player_122.png", horizontal=True)
image player 123f = im.Flip("characters/player/char_player_123.png", horizontal=True)
image player 124f = im.Flip("characters/player/char_player_124.png", horizontal=True)
image player 125f = im.Flip("characters/player/char_player_125.png", horizontal=True)
image player 126f = im.Flip("characters/player/char_player_126.png", horizontal=True)
image player 127f = im.Flip("characters/player/char_player_127.png", horizontal=True)
image player 128f = im.Flip("characters/player/char_player_128.png", horizontal=True)
image player 129f = im.Flip("characters/player/char_player_129.png", horizontal=True)
image player 130f = im.Flip("characters/player/char_player_130.png", horizontal=True)
image player 131f = im.Flip("characters/player/char_player_131.png", horizontal=True)
image player 132f = im.Flip("characters/player/char_player_132.png", horizontal=True)
image player 133f = im.Flip("characters/player/char_player_133.png", horizontal=True)
image player 134f = im.Flip("characters/player/char_player_134.png", horizontal=True)
image player 135f = im.Flip("characters/player/char_player_135.png", horizontal=True)
image player 136f = im.Flip("characters/player/char_player_136.png", horizontal=True)
image player 137f = im.Flip("characters/player/char_player_137.png", horizontal=True)
image player 138f = im.Flip("characters/player/char_player_138.png", horizontal=True)
image player 139f = im.Flip("characters/player/char_player_139.png", horizontal=True)
image player 140f = im.Flip("characters/player/char_player_140.png", horizontal=True)
image player 141f = im.Flip("characters/player/char_player_141.png", horizontal=True)
image player 142f = im.Flip("characters/player/char_player_142.png", horizontal=True)
image player 143f = im.Flip("characters/player/char_player_143.png", horizontal=True)
image player 144f = im.Flip("characters/player/char_player_144.png", horizontal=True)
image player 145f = im.Flip("characters/player/char_player_145.png", horizontal=True)
image player 146f = im.Flip("characters/player/char_player_146.png", horizontal=True)
image player 147f = im.Flip("characters/player/char_player_147.png", horizontal=True)
image player 148f = im.Flip("characters/player/char_player_148.png", horizontal=True)
image player 149f = im.Flip("characters/player/char_player_149.png", horizontal=True)
image player 150f = im.Flip("characters/player/char_player_150.png", horizontal=True)
image player 151f = im.Flip("characters/player/char_player_151.png", horizontal=True)
image player 152f = im.Flip("characters/player/char_player_152.png", horizontal=True)
image player 153f = im.Flip("characters/player/char_player_153.png", horizontal=True)
image player 154f = im.Flip("characters/player/char_player_154.png", horizontal=True)
image player 155f = im.Flip("characters/player/char_player_155.png", horizontal=True)
image player 156f = im.Flip("characters/player/char_player_156.png", horizontal=True)
image player 157f = im.Flip("characters/player/char_player_157.png", horizontal=True)
image player 158f = im.Flip("characters/player/char_player_158.png", horizontal=True)
image player 159f = im.Flip("characters/player/char_player_159.png", horizontal=True)
image player 160f = im.Flip("characters/player/char_player_160.png", horizontal=True)
image player 161f = im.Flip("characters/player/char_player_161.png", horizontal=True)
image player 162f = im.Flip("characters/player/char_player_162.png", horizontal=True)
image player 163f = im.Flip("characters/player/char_player_163.png", horizontal=True)
image player 164f = im.Flip("characters/player/char_player_164.png", horizontal=True)
image player 165f = im.Flip("characters/player/char_player_165.png", horizontal=True)
image player 166f = im.Flip("characters/player/char_player_166.png", horizontal=True)
image player 167f = im.Flip("characters/player/char_player_167.png", horizontal=True)
image player 168f = im.Flip("characters/player/char_player_168.png", horizontal=True)
image player 192f = im.Flip("characters/player/char_player_192.png", horizontal=True)
image player 203f = im.Flip("characters/player/char_player_203.png", horizontal=True)
image player 209f = im.Flip("characters/player/char_player_209.png", horizontal=True)
image player 210f = im.Flip("characters/player/char_player_210.png", horizontal=True)
image player 212f = im.Flip("characters/player/char_player_212.png", horizontal=True)
image player 239f = im.Flip("characters/player/char_player_239.png",xoffset=-5,horizontal=True)
image player 240f = im.Flip("characters/player/char_player_240.png",xoffset=-5,horizontal=True)
image player 261f = im.Flip("characters/player/char_player_261.png", horizontal=True)
image player 263f = im.Flip("characters/player/char_player_263.png", horizontal=True)
image player 367f = im.Flip("characters/player/char_player_367.png", horizontal=True)
image player 368f = im.Flip("characters/player/char_player_368.png", horizontal=True)
image player 384f = im.Flip("characters/player/char_player_384.png", horizontal=True)
image player 385f = im.Flip("characters/player/char_player_385.png", horizontal=True)
image player 428f = im.Flip("characters/player/char_player_428.png", horizontal=True)
image player 430f = im.Flip("characters/player/char_player_430.png", horizontal=True)
image player 430bf = im.Flip("characters/player/char_player_430b.png", horizontal=True)
image player 434f = im.Flip("characters/player/char_player_434.png", horizontal=True)
image player 435f = im.Flip("characters/player/char_player_435.png", horizontal=True)
image player 444f = im.Flip("characters/player/char_player_444.png", horizontal=True)
image players robe f = im.Flip("characters/player/char_player_445.png", horizontal=True)
image player 455f = im.Flip("characters/player/char_player_455.png", horizontal=True)
image player 456f = im.Flip("characters/player/char_player_456.png", horizontal=True)
image player 457f = im.Flip("characters/player/char_player_457.png", horizontal=True)
image player 458f = im.Flip("characters/player/char_player_458.png", horizontal=True)
image player 460f = im.Flip("characters/player/char_player_460.png", horizontal=True)
image player 461f = im.Flip("characters/player/char_player_461.png", horizontal=True)
image player 494f = im.Flip("characters/player/char_player_494.png", horizontal=True)
image player 495f = im.Flip("characters/player/char_player_495.png", horizontal=True)

image playerf 1f = im.Flip("characters/player/char_player_front_01.png", horizontal=True)
image playerf 1bf = im.Flip("characters/player/char_player_front_01b.png", horizontal=True)
image playerf 2flip = im.Flip("characters/player/char_player_front_02.png", horizontal=True)
image playerf 2bf = im.Flip("characters/player/char_player_front_02b.png", horizontal=True)
image playerf 2cf = im.Flip("characters/player/char_player_front_02c.png", horizontal=True)
image playerf 2df = im.Flip("characters/player/char_player_front_02d.png", horizontal=True)
image playerf 2ef = im.Flip("characters/player/char_player_front_02e.png", horizontal=True)
image playerf 2ff = im.Flip("characters/player/char_player_front_02f.png", horizontal=True)
image playerf 3f = im.Flip("characters/player/char_player_front_03.png", horizontal=True)
image playerf 3bf = im.Flip("characters/player/char_player_front_03b.png", horizontal=True)
image playerf 3cf = im.Flip("characters/player/char_player_front_03c.png", horizontal=True)
image playerf 4flip = im.Flip("characters/player/char_player_front_04.png", horizontal=True)
image playerf 4bf = im.Flip("characters/player/char_player_front_04b.png", horizontal=True)
image playerf 4cf = im.Flip("characters/player/char_player_front_04c.png", horizontal=True)
image playerf 4df = im.Flip("characters/player/char_player_front_04d.png", horizontal=True)
image playerf 4ef = im.Flip("characters/player/char_player_front_04e.png", horizontal=True)
image playerf 4ff = im.Flip("characters/player/char_player_front_04f.png", horizontal=True)
image playerf 4gf = im.Flip("characters/player/char_player_front_04g.png", horizontal=True)
image playerf 4hf = im.Flip("characters/player/char_player_front_04h.png", horizontal=True)
image playerf 5f = im.Flip("characters/player/char_player_front_05.png", horizontal=True)
image playerf 5bf = im.Flip("characters/player/char_player_front_05b.png", horizontal=True)
image playerf 6f = im.Flip("characters/player/char_player_front_06.png", horizontal=True)

image playerfa 1f = im.Flip("characters/player/char_player_front_arms_01.png", horizontal=True)
image playerfa 2f = im.Flip("characters/player/char_player_front_arms_02.png", horizontal=True)

image playerfb 1f = im.Flip("characters/player/char_player_front_boner_01.png", horizontal=True)
image playerfb 2f = im.Flip("characters/player/char_player_front_boner_02.png", horizontal=True)
image playerfb 3f = im.Flip("characters/player/char_player_front_boner_03.png", horizontal=True)



image jersey 10f = im.Flip("characters/jersey/char_jersey_10.png", horizontal=True)
image jersey 11f = im.Flip("characters/jersey/char_jersey_11.png", horizontal=True)
image jersey 12f = im.Flip("characters/jersey/char_jersey_12.png", horizontal=True)
image jersey 13f = im.Flip("characters/jersey/char_jersey_13.png", horizontal=True)
image jersey 17f = im.Flip("characters/jersey/char_jersey_17.png", horizontal=True)
image jersey 18f = im.Flip("characters/jersey/char_jersey_18.png", horizontal=True)
image jersey 19f = im.Flip("characters/jersey/char_jersey_19.png", horizontal=True)
image jersey 20f = im.Flip("characters/jersey/char_jersey_20.png", horizontal=True)
image jersey 22f = im.Flip("characters/jersey/char_jersey_22.png", horizontal=True)
image jersey 23f = im.Flip("characters/jersey/char_jersey_23.png", horizontal=True)
image jersey 27f = im.Flip("characters/jersey/char_jersey_27.png", horizontal=True)
image jersey 28f = im.Flip("characters/jersey/char_jersey_28.png", horizontal=True)
image jersey 29f = im.Flip("characters/jersey/char_jersey_29.png", horizontal=True)
image jersey 30f = im.Flip("characters/jersey/char_jersey_30.png", horizontal=True)
image jersey 31f = im.Flip("characters/jersey/char_jersey_31.png", horizontal=True)
image jersey 32f = im.Flip("characters/jersey/char_jersey_32.png", horizontal=True)


image master 2f = im.Flip("characters/master/char_master_02.png", horizontal=True)
image master 3f = im.Flip("characters/master/char_master_03.png", horizontal=True)
image master 4f = im.Flip("characters/master/char_master_04.png", horizontal=True)
image master 6f = im.Flip("characters/master/char_master_06.png", horizontal=True)
image master 10f = im.Flip("characters/master/char_master_10.png", horizontal=True)


image mia 7f = im.Flip("characters/mia/char_mia_07.png", horizontal=True)
image mia 8f = im.Flip("characters/mia/char_mia_08.png", horizontal=True)
image mia 9f = im.Flip("characters/mia/char_mia_09.png", horizontal=True)
image mia 10f = im.Flip("characters/mia/char_mia_10.png", horizontal=True)
image mia 12f = im.Flip("characters/mia/char_mia_12.png", horizontal=True)
image mia 30f = im.Flip("characters/mia/char_mia_30.png", horizontal=True)
image mia 40f = im.Flip("characters/mia/char_mia_40.png", horizontal=True)
image mia 41f = im.Flip("characters/mia/char_mia_41.png", horizontal=True)
image mia 42f = im.Flip("characters/mia/char_mia_42.png", horizontal=True)
image mia 43f = im.Flip("characters/mia/char_mia_43.png", horizontal=True)
image mia 44f = im.Flip("characters/mia/char_mia_44.png", horizontal=True)
image mia 45f = im.Flip("characters/mia/char_mia_45.png", horizontal=True)
image mia 46f = im.Flip("characters/mia/char_mia_46.png", horizontal=True)
image mia 47f = im.Flip("characters/mia/char_mia_47.png", horizontal=True)
image mia 48f = im.Flip("characters/mia/char_mia_48.png", horizontal=True)


image helen 1f = im.Flip("characters/helen/char_helen_01.png", horizontal=True)
image helen 5f = im.Flip("characters/helen/char_helen_05.png", horizontal=True)
image helen 6f = im.Flip("characters/helen/char_helen_06.png", horizontal=True)
image helen 7f = im.Flip("characters/helen/char_helen_07.png", horizontal=True)
image helen 8f = im.Flip("characters/helen/char_helen_08.png", horizontal=True)
image helen 9f = im.Flip("characters/helen/char_helen_09.png", horizontal=True)
image helen 10f = im.Flip("characters/helen/char_helen_10.png", horizontal=True)
image helen 11f = im.Flip("characters/helen/char_helen_11.png", horizontal=True)


image harold 1f = im.Flip("characters/harold/char_harold_01.png", horizontal=True)
image harold 2f = im.Flip("characters/harold/char_harold_02.png", horizontal=True)
image harold 3f = im.Flip("characters/harold/char_harold_03.png", horizontal=True)
image harold 4f = im.Flip("characters/harold/char_harold_04.png", horizontal=True)
image harold 25f = im.Flip("characters/harold/char_harold_25.png", horizontal=True)
image harold 26f = im.Flip("characters/harold/char_harold_26.png", horizontal=True)


image mom 1f = im.Flip("characters/mom/char_mom_01.png", horizontal=True)
image mom 2f = im.Flip("characters/mom/char_mom_02.png", horizontal=True)
image mom 3f = im.Flip("characters/mom/char_mom_03.png", horizontal=True)
image mom 13f = im.Flip( "characters/mom/char_mom_13.png", horizontal=True)
image mom 14f = im.Flip( "characters/mom/char_mom_14.png", horizontal=True)
image mom 14bf = im.Flip("characters/mom/char_mom_14b.png", horizontal=True)
image mom 15f = im.Flip("characters/mom/char_mom_15.png", horizontal=True)
image mom 16f = im.Flip("characters/mom/char_mom_16.png", horizontal=True)
image mom 17f = im.Flip("characters/mom/char_mom_17.png", horizontal=True)
image mom 18f = im.Flip("characters/mom/char_mom_18.png", horizontal=True)
image mom 19f = im.Flip("characters/mom/char_mom_19.png", horizontal=True)
image mom 20f = im.Flip("characters/mom/char_mom_20.png", horizontal=True)
image mom 38f = im.Flip("characters/mom/char_mom_38.png", horizontal=True)
image mom 39f = im.Flip("characters/mom/char_mom_39.png", horizontal=True)
image mom 59f = im.Flip("characters/mom/char_mom_59.png", horizontal=True)
image mom 60f = im.Flip("characters/mom/char_mom_60.png", horizontal=True)
image mom 61f = im.Flip("characters/mom/char_mom_61.png", horizontal=True)
image mom 62f = im.Flip("characters/mom/char_mom_62.png", horizontal=True)
image mom 63f = im.Flip("characters/mom/char_mom_63.png", horizontal=True)
image mom 91f = im.Flip("characters/mom/char_mom_91.png", horizontal=True)
image mom 92f = im.Flip("characters/mom/char_mom_92.png", horizontal=True)
image mom 93f = im.Flip("characters/mom/char_mom_93.png", horizontal=True)
image mom 125f = im.Flip("characters/mom/char_mom_125.png", horizontal=True)
image mom 164f = im.Flip("characters/mom/char_mom_164.png", horizontal=True)
image mom 165f = im.Flip("characters/mom/char_mom_165.png", horizontal=True)
image mom 166f = im.Flip("characters/mom/char_mom_166.png", horizontal=True)
image mom 168f = im.Flip("characters/mom/char_mom_168.png", horizontal=True)
image mom 169f = im.Flip("characters/mom/char_mom_169.png", horizontal=True)
image mom 169bf = im.Flip("characters/mom/char_mom_169b.png", horizontal=True)
image mneck 1f = im.Flip("characters/mom/char_mom_176.png", horizontal=True)
image mom 183bf = im.Flip("characters/mom/char_mom_183b.png", horizontal=True)
image mom 184cf = im.Flip("characters/mom/char_mom_184c.png", horizontal=True)
image mom 184df = im.Flip("characters/mom/char_mom_184d.png", horizontal=True)
image mom 188f = im.Flip("characters/mom/char_mom_188.png",xoffset=130, horizontal=True)
image mom 189f = im.Flip("characters/mom/char_mom_189.png",xoffset=130, horizontal=True)
image mom 190f = im.Flip("characters/mom/char_mom_190.png", horizontal=True)
image mom 191f = im.Flip("characters/mom/char_mom_191.png", horizontal=True)
image mom_robe 191bf = im.Flip("characters/mom/char_mom_191b.png",xoffset=-241,yoffset=-42, horizontal=True)
image mom 192f = im.Flip("characters/mom/char_mom_192.png", horizontal=True)
image mom 193f = im.Flip("characters/mom/char_mom_193.png", horizontal=True)
image player finger 193bf = im.Flip("characters/mom/char_mom_193b.png",xoffset=41,yoffset=-1, horizontal=True)
image mom 194f = im.Flip("characters/mom/char_mom_194.png", horizontal=True)
image mom_robe 194bf = im.Flip("characters/mom/char_mom_194b.png",xoffset=-268,yoffset=-42, horizontal=True)
image mom 195f = im.Flip("characters/mom/char_mom_195.png", horizontal=True)
image mom_robe 195bf = im.Flip("characters/mom/char_mom_195b.png",xoffset=-268,yoffset=-40, horizontal=True)
image mom 196f = im.Flip("characters/mom/char_mom_196.png", horizontal=True)
image mom_robe 196bf = im.Flip("characters/mom/char_mom_196b.png",xoffset=-269,yoffset=-39, horizontal=True)
image mom 197f = im.Flip("characters/mom/char_mom_197.png",yoffset=-29, horizontal=True)
image mom_robe 197bf = im.Flip("characters/mom/char_mom_197b.png",xoffset=-279,yoffset=-49, horizontal=True)
image mom 197cf = im.Flip("characters/mom/char_mom_197c.png",yoffset=-24, horizontal=True)
image mom 197df = im.Flip("characters/mom/char_mom_197d.png",yoffset=-24, horizontal=True)
image mom 197ef = im.Flip("characters/mom/char_mom_197e.png",yoffset=-24, horizontal=True)
image mom 197ff = im.Flip("characters/mom/char_mom_197f.png",yoffset=-24, horizontal=True)
image mom 208f = im.Flip("characters/mom/char_mom_208.png", horizontal=True)

image momf 1f = im.Flip("characters/mom/char_mom_front_01.png", horizontal=True)
image momf 2f = im.Flip("characters/mom/char_mom_front_02.png", horizontal=True)
image momf 2bf = im.Flip("characters/mom/char_mom_front_02b.png", horizontal=True)
image momf 3f = im.Flip("characters/mom/char_mom_front_03.png", horizontal=True)
image momf 3bf = im.Flip("characters/mom/char_mom_front_03b.png", horizontal=True)
image momf 4f = im.Flip("characters/mom/char_mom_front_04.png", horizontal=True)
image momf 4bf = im.Flip("characters/mom/char_mom_front_04b.png", horizontal=True)
image momf 4cf = im.Flip("characters/mom/char_mom_front_04c.png", horizontal=True)
image momf 5flip = im.Flip("characters/mom/char_mom_front_05.png", horizontal=True)
image momf 5bf = im.Flip("characters/mom/char_mom_front_05b.png", horizontal=True)
image momf 5cf = im.Flip("characters/mom/char_mom_front_05c.png", horizontal=True)
image momf 5df = im.Flip("characters/mom/char_mom_front_05d.png", horizontal=True)
image momf 5ef = im.Flip("characters/mom/char_mom_front_05e.png", horizontal=True)
image momf 5ff = im.Flip("characters/mom/char_mom_front_05f.png", horizontal=True)
image momf 5gf = im.Flip("characters/mom/char_mom_front_05g.png", horizontal=True)
image momf 6f = im.Flip("characters/mom/char_mom_front_06.png", horizontal=True)
image momf 7f = im.Flip("characters/mom/char_mom_front_07.png", horizontal=True)
image momf 7bf = im.Flip("characters/mom/char_mom_front_07b.png", horizontal=True)
image momf 8flip = im.Flip("characters/mom/char_mom_front_08.png", horizontal=True)
image momf 8bf = im.Flip("characters/mom/char_mom_front_08b.png", horizontal=True)
image momf 8cf = im.Flip("characters/mom/char_mom_front_08c.png", horizontal=True)
image momf 8df = im.Flip("characters/mom/char_mom_front_08d.png", horizontal=True)
image momf 8ef = im.Flip("characters/mom/char_mom_front_08e.png", horizontal=True)
image momf 8ff = im.Flip("characters/mom/char_mom_front_08f.png", horizontal=True)
image momf 8gf = im.Flip("characters/mom/char_mom_front_08g.png", horizontal=True)
image momf 9f = im.Flip("characters/mom/char_mom_front_09.png", horizontal=True)
image momf 10f = im.Flip("characters/mom/char_mom_front_10.png", horizontal=True)
image momf 11f = im.Flip("characters/mom/char_mom_front_11.png", horizontal=True)
image momf 12f = im.Flip("characters/mom/char_mom_front_12.png", horizontal=True)

image momfa 1f = im.Flip("characters/mom/char_mom_front_arms_01.png", horizontal=True)
image momfa 2f = im.Flip("characters/mom/char_mom_front_arms_02.png", horizontal=True)
image momfa 3f = im.Flip("characters/mom/char_mom_front_arms_03.png", horizontal=True)
image momfa 3bf = im.Flip("characters/mom/char_mom_front_arms_03b.png", horizontal=True)
image momfa 4f = im.Flip("characters/mom/char_mom_front_arms_04.png", horizontal=True)
image momfa 5f = im.Flip("characters/mom/char_mom_front_arms_05.png", horizontal=True)
image momfa 5bf = im.Flip("characters/mom/char_mom_front_arms_05b.png", horizontal=True)
image momfa 5cf = im.Flip("characters/mom/char_mom_front_arms_05c.png", horizontal=True)


image sis 1f = im.Flip("characters/sis/char_sis_01.png", horizontal=True)
image sis 2f = im.Flip("characters/sis/char_sis_02.png", horizontal=True)
image sis 3f = im.Flip("characters/sis/char_sis_03.png", horizontal=True)
image sis 6f = im.Flip("characters/sis/char_sis_06.png", horizontal=True)
image sis 7f = im.Flip("characters/sis/char_sis_07.png", horizontal=True)
image sis 8f = im.Flip("characters/sis/char_sis_08.png", horizontal=True)
image sis 9f = im.Flip("characters/sis/char_sis_09.png", horizontal=True)
image sis 10f = im.Flip("characters/sis/char_sis_10.png", horizontal=True)
image sis 11f = im.Flip("characters/sis/char_sis_11.png", horizontal=True)
image sis 12f = im.Flip("characters/sis/char_sis_12.png", horizontal=True)
image sis 13f = im.Flip("characters/sis/char_sis_13.png", horizontal=True)
image sis 14f = im.Flip("characters/sis/char_sis_14.png", horizontal=True)
image sis 15f = im.Flip("characters/sis/char_sis_15.png", horizontal=True)
image sis 16f = im.Flip("characters/sis/char_sis_16.png", horizontal=True)
image sis 17f = im.Flip("characters/sis/char_sis_17.png", horizontal=True)
image sis 18f = im.Flip("characters/sis/char_sis_18.png", horizontal=True)
image sis 19f = im.Flip("characters/sis/char_sis_19.png", horizontal=True)
image sis 49f = im.Flip("characters/sis/char_sis_49.png", horizontal=True)


image judith 1f = im.Flip("characters/judith/char_judith_01.png", horizontal=True)
image judith 2f = im.Flip("characters/judith/char_judith_02.png", horizontal=True)
image judith 3f = im.Flip("characters/judith/char_judith_03.png", horizontal=True)
image judith 4f = im.Flip("characters/judith/char_judith_04.png", horizontal=True)
image judith 5f = im.Flip("characters/judith/char_judith_05.png", horizontal=True)
image judith 6f = im.Flip("characters/judith/char_judith_06.png", horizontal=True)
image judith 7f = im.Flip("characters/judith/char_judith_07.png", horizontal=True)
image judith 8f = im.Flip("characters/judith/char_judith_08.png", horizontal=True)
image judith 9f = im.Flip("characters/judith/char_judith_09.png", horizontal=True)
image judith 10f = im.Flip("characters/judith/char_judith_10.png", horizontal=True)


image erik 1f = im.Flip("characters/erik/char_erik_01.png", horizontal=True)
image erik 2f = im.Flip("characters/erik/char_erik_02.png", horizontal=True)
image erik 3f = im.Flip("characters/erik/char_erik_03.png", horizontal=True)
image erik 4f = im.Flip("characters/erik/char_erik_04.png", horizontal=True)
image erik 5f = im.Flip("characters/erik/char_erik_05.png", horizontal=True)
image erik 5bf = im.Flip("characters/erik/char_erik_05b.png", horizontal=True)
image erik 6f = im.Flip("characters/erik/char_erik_06.png", horizontal=True)
image erik 7f = im.Flip("characters/erik/char_erik_07.png", horizontal=True)
image erik 8f = im.Flip("characters/erik/char_erik_08.png", horizontal=True)
image erik 9f = im.Flip("characters/erik/char_erik_09.png", horizontal=True)
image erik 10f = im.Flip("characters/erik/char_erik_10.png", horizontal=True)
image erik 11f = im.Flip("characters/erik/char_erik_11.png", horizontal=True)
image erik 12f = im.Flip("characters/erik/char_erik_12.png", horizontal=True)
image erik 13f = im.Flip("characters/erik/char_erik_13.png", horizontal=True)
image erik 14f = im.Flip("characters/erik/char_erik_14.png", horizontal=True)
image erik 15f = im.Flip( "characters/erik/char_erik_15.png", horizontal=True)
image erik 15bf = im.Flip( "characters/erik/char_erik_15b.png", horizontal=True)
image erik 51f = im.Flip("characters/erik/char_erik_51.png", horizontal=True)
image erik 55f = im.Flip("characters/erik/char_erik_55.png", horizontal=True)
image erik 56f = im.Flip( "characters/erik/char_erik_56.png", horizontal=True)
image erik 57f = im.Flip( "characters/erik/char_erik_57.png", horizontal=True)
image erik 58f = im.Flip( "characters/erik/char_erik_58.png", horizontal=True)
image erik 59f = im.Flip("characters/erik/char_erik_59.png", horizontal=True)
image erik 60f = im.Flip("characters/erik/char_erik_60.png", horizontal=True)


image principal 1f = im.Flip( "characters/principal/char_principal_01.png", horizontal=True)
image principal 2f = im.Flip( "characters/principal/char_principal_02.png", horizontal=True)
image principal 3f = im.Flip( "characters/principal/char_principal_03.png", horizontal=True)
image principal 4f = im.Flip( "characters/principal/char_principal_04.png", horizontal=True)
image principal 5f = im.Flip( "characters/principal/char_principal_05.png", horizontal=True)
image principal 6f = im.Flip( "characters/principal/char_principal_06.png", horizontal=True)
image principal 7f = im.Flip( "characters/principal/char_principal_07.png", horizontal=True)
image principal 8f = im.Flip( "characters/principal/char_principal_08.png", horizontal=True)
image principal 9f = im.Flip( "characters/principal/char_principal_09.png", horizontal=True)
image principal 10f = im.Flip( "characters/principal/char_principal_10.png", horizontal=True)
image principal 11f = im.Flip( "characters/principal/char_principal_11.png", horizontal=True)
image principal 12f = im.Flip( "characters/principal/char_principal_12.png", horizontal=True)
image principal 13f = im.Flip( "characters/principal/char_principal_13.png", horizontal=True)
image principal 14f = im.Flip( "characters/principal/char_principal_14.png", horizontal=True)
image principal 15f = im.Flip( "characters/principal/char_principal_15.png", horizontal=True)
image principal 16f = im.Flip( "characters/principal/char_principal_16.png", horizontal=True)
image principal 17f = im.Flip( "characters/principal/char_principal_17.png", horizontal=True)
image principal 18f = im.Flip( "characters/principal/char_principal_18.png", horizontal=True)
image principal 19f = im.Flip( "characters/principal/char_principal_19.png", horizontal=True)
image principal 20f = im.Flip( "characters/principal/char_principal_20.png", horizontal=True)
image principal 21f = im.Flip( "characters/principal/char_principal_21.png", horizontal=True)
image principal 22f = im.Flip( "characters/principal/char_principal_22.png", horizontal=True)
image principal 23f = im.Flip( "characters/principal/char_principal_23.png", horizontal=True)
image principal 24f = im.Flip( "characters/principal/char_principal_24.png", horizontal=True)
image principal 25f = im.Flip( "characters/principal/char_principal_25.png", horizontal=True)
image principal 26f = im.Flip( "characters/principal/char_principal_26.png", horizontal=True)
image principal 27f = im.Flip( "characters/principal/char_principal_27.png", horizontal=True)
image principal 28f = im.Flip( "characters/principal/char_principal_28.png", horizontal=True)


image yumi 1f = im.Flip("characters/yumi/char_yumi_01.png", horizontal=True)
image yumi 2f = im.Flip("characters/yumi/char_yumi_02.png", horizontal=True)
image yumi 5f = im.Flip("characters/yumi/char_yumi_05.png", horizontal=True)
image yumi 6f = im.Flip("characters/yumi/char_yumi_06.png", horizontal=True)
image yum 12f = im.Flip("characters/yumi/char_yumi_12.png", horizontal=True)
image yum 13f = im.Flip("characters/yumi/char_yumi_13.png", horizontal=True)
image yum 14f = im.Flip("characters/yumi/char_yumi_14.png", horizontal=True)


image sara 4f = im.Flip("characters/sara/char_sara_04.png", horizontal=True)
image sara 5f = im.Flip("characters/sara/char_sara_05.png", horizontal=True)


image tstand 1f = im.Flip("characters/terry/char_terry_standing_01.png", horizontal=True)
image tstand 2f = im.Flip("characters/terry/char_terry_standing_02.png", horizontal=True)
image tstand 3f = im.Flip("characters/terry/char_terry_standing_03.png", horizontal=True)


image titty 1f = im.Flip( "characters/titty/char_titty_01.png", horizontal=True)


image erikmom 1f = im.Flip( "characters/erikmom/char_erikmom_01.png", horizontal=True)
image erikmom 2f = im.Flip( "characters/erikmom/char_erikmom_02.png", horizontal=True)
image erikmom 3f = im.Flip( "characters/erikmom/char_erikmom_03.png", horizontal=True)
image erikmom 4f = im.Flip( "characters/erikmom/char_erikmom_04.png", horizontal=True)
image erikmom 5f = im.Flip( "characters/erikmom/char_erikmom_05.png", horizontal=True)
image erikmom 6f = im.Flip( "characters/erikmom/char_erikmom_06.png", horizontal=True)
image erikmom 7f = im.Flip( "characters/erikmom/char_erikmom_07.png", horizontal=True)
image erikmom 8f = im.Flip( "characters/erikmom/char_erikmom_08.png", horizontal=True)
image erikmom 9f = im.Flip( "characters/erikmom/char_erikmom_09.png", horizontal=True)
image erikmom 10f = im.Flip( "characters/erikmom/char_erikmom_10.png", horizontal=True)
image erikmom 11f = im.Flip( "characters/erikmom/char_erikmom_11.png", horizontal=True)
image erikmom 12f = im.Flip( "characters/erikmom/char_erikmom_12.png", horizontal=True)
image erikmom 13f = im.Flip( "characters/erikmom/char_erikmom_13.png", horizontal=True)
image erikmom 14f = im.Flip( "characters/erikmom/char_erikmom_14.png", horizontal=True)
image erikmom 15f = im.Flip( "characters/erikmom/char_erikmom_15.png", horizontal=True)
image erikmom 16f = im.Flip( "characters/erikmom/char_erikmom_16.png", horizontal=True)
image erikmom 17f = im.Flip( "characters/erikmom/char_erikmom_17.png", horizontal=True)
image erikmom 18f = im.Flip( "characters/erikmom/char_erikmom_18.png", horizontal=True)
image erikmom 19f = im.Flip( "characters/erikmom/char_erikmom_19.png", horizontal=True)
image erikmom 20f = im.Flip( "characters/erikmom/char_erikmom_20.png", horizontal=True)
image erikmom 21f = im.Flip( "characters/erikmom/char_erikmom_21.png", horizontal=True)
image erikmom 22f = im.Flip( "characters/erikmom/char_erikmom_22.png", horizontal=True)
image erikmom 23f = im.Flip( "characters/erikmom/char_erikmom_23.png", horizontal=True)
image erikmom 24f = im.Flip( "characters/erikmom/char_erikmom_24.png", horizontal=True)
image erikmom 25f = im.Flip( "characters/erikmom/char_erikmom_25.png", horizontal=True)
image erikmom 26f = im.Flip( "characters/erikmom/char_erikmom_26.png", horizontal=True)
image erikmom 27f = im.Flip( "characters/erikmom/char_erikmom_27.png", horizontal=True)
image erikmom 28f = im.Flip( "characters/erikmom/char_erikmom_28.png", horizontal=True)
image erikmom 29f = im.Flip( "characters/erikmom/char_erikmom_29.png", horizontal=True)
image erikmom 30f = im.Flip( "characters/erikmom/char_erikmom_30.png", horizontal=True)
image erikmom 31f = im.Flip( "characters/erikmom/char_erikmom_31.png", horizontal=True)
image erikmom 32f = im.Flip( "characters/erikmom/char_erikmom_32.png", horizontal=True)
image erikmom 33f = im.Flip( "characters/erikmom/char_erikmom_33.png", horizontal=True)
image erikmom 34f = im.Flip( "characters/erikmom/char_erikmom_34.png", horizontal=True)
image erikmom 35f = im.Flip( "characters/erikmom/char_erikmom_35.png", horizontal=True)


image harold 1f = im.Flip( "characters/harold/char_harold_01.png", horizontal=True)
image harold 3f = im.Flip( "characters/harold/char_harold_03.png", horizontal=True)


image henchman1 6f = im.Flip("characters/henchman/char_henchman_06.png", horizontal=True)


image annie 8f = im.Flip( "characters/annie/char_annie_08.png", horizontal=True)


image ang 1f = im.Flip("characters/angelica/char_angelica_01.png", horizontal=True)
image ang 2f = im.Flip("characters/angelica/char_angelica_02.png", horizontal=True)
image ang 5f = im.Flip("characters/angelica/char_angelica_05.png", horizontal=True)
image ang 6f = im.Flip("characters/angelica/char_angelica_06.png", horizontal=True)
image ang 7f = im.Flip("characters/angelica/char_angelica_07.png", horizontal=True)
image ang 8f = im.Flip("characters/angelica/char_angelica_08.png", horizontal=True)
image ang 9f = im.Flip("characters/angelica/char_angelica_09.png", horizontal=True)
image ang 10f = im.Flip("characters/angelica/char_angelica_10.png", horizontal=True)
image ang 17f = im.Flip("characters/angelica/char_angelica_17.png", horizontal=True)
image ang 18f = im.Flip("characters/angelica/char_angelica_18.png", horizontal=True)
image ang 21f = im.Flip("characters/angelica/char_angelica_21.png", horizontal=True)
image ang 22f = im.Flip("characters/angelica/char_angelica_22.png", horizontal=True)
image ang 23f = im.Flip("characters/angelica/char_angelica_23.png", horizontal=True)
image ang 24f = im.Flip("characters/angelica/char_angelica_24.png", horizontal=True)
image ang 25f = im.Flip("characters/angelica/char_angelica_25.png", horizontal=True)
image ang 25bf = im.Flip("characters/angelica/char_angelica_25b.png", horizontal=True)
image ang 26f = im.Flip("characters/angelica/char_angelica_26.png", horizontal=True)
image ang 26bf = im.Flip("characters/angelica/char_angelica_26b.png", horizontal=True)
image ang 33f = im.Flip("characters/angelica/char_angelica_33.png", horizontal=True)
image ang 34f = im.Flip("characters/angelica/char_angelica_34.png", horizontal=True)
image helen whip 3 = im.Flip("characters/angelica/char_angelica_21.png", horizontal=True)


image anna 4f = im.Flip( "characters/anna/char_anna_04.png", horizontal=True)
image anna 5f = im.Flip( "characters/anna/char_anna_05.png", horizontal=True)
image anna 8f = im.Flip( "characters/anna/char_anna_08.png", horizontal=True)
image anna 12f = im.Flip( "characters/anna/char_anna_12.png", horizontal=True)


image becca 1f = im.Flip("characters/becca/char_becca_01.png", horizontal=True)
image becca 2f = im.Flip("characters/becca/char_becca_02.png", horizontal=True)
image becca 3f = im.Flip("characters/becca/char_becca_03.png", horizontal=True)
image becca 4f = im.Flip("characters/becca/char_becca_04.png", horizontal=True)


image missy 1f = im.Flip("characters/missy/char_missy_01.png", horizontal=True)
image missy 2f = im.Flip("characters/missy/char_missy_02.png", horizontal=True)
image missy 3f = im.Flip("characters/missy/char_missy_03.png", horizontal=True)
image missy 4f = im.Flip("characters/missy/char_missy_04.png", horizontal=True)